#r @"C:\Users\Chris\.nuget\packages\fparsec\1.1.1\lib\net45\FParsecCS.dll"
#r @"C:\Users\Chris\.nuget\packages\fparsec\1.1.1\lib\net45\FParsec.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Core.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Data.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Drawing.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.IO.Compression.FileSystem.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Numerics.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Runtime.Serialization.dll"
#r @"C:\Users\Chris\.nuget\packages\system.valuetuple\4.5.0\ref\net461\System.ValueTuple.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Xml.Linq.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Xml.dll"
#r @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.dll"
#r @"C:\Users\Chris\.nuget\packages\taskbuilder.fs\2.1.0\lib\net46\TaskBuilder.fs.dll"
#load @"c:\Users\Chris\OneDrive\BitBucket\FSIRC-Client\FSIRC\Types.fs"
#load @"c:\Users\Chris\OneDrive\BitBucket\FSIRC-Client\FSIRC\TCP.fs"
#load @"c:\Users\Chris\OneDrive\BitBucket\FSIRC-Client\FSIRC\Parsing.fs"
#load @"c:\Users\Chris\OneDrive\BitBucket\FSIRC-Client\FSIRC\IRC.fs"
#load @"c:\Users\Chris\OneDrive\BitBucket\FSIRC-Client\FSIRC\FSIRC.fs"